@echo off

echo This uninstaller will only function when placed inside the UT2004 root folder (so where folders like Textures, Staticmeshes etc are stored)

pause

del Animations\BallisticThird.ukx
del Animations\BW_Core_WeaponAnim.ukx
del Animations\BWBP_CC_Anim.ukx
del Animations\BWBP_JCF_Anims.ukx
del Animations\BWBP_JW_Anim.ukx
del Animations\BWBP_OP_Anim.ukx
del Animations\BWBP_SKC_Anim.ukx
del Animations\BWBP_SKC_AnimExp.ukx
del Animations\BWBP_SWC_Anims.ukx
del Animations\BWBP_APC_Anim.ukx
del Animations\BWBP_Vehicles_Anim.ukx
del Animations\BWGuyAnim.ukx

del Animations\BallisticAnims_25.ukx
del Animations\BallisticAnims2.ukx
del Animations\BallisticAnims3.ukx
del Animations\BallisticProAnims.ukx
del Animations\BallisticRecolors4AnimPro.ukx
del Animations\BallisticRecolors4AnimProExp.ukx
del Animations\BallisticThird.ukx
del Animations\BEVehicleAnims.ukx
del Animations\BEVehicleAnimsV13.ukx
del Animations\BEVehicleAnimsV14.ukx
del Animations\BWBP1-Anims.ukx
del Animations\BWBP2b-Anims.ukx
del Animations\BWBP3b-Anims.ukx
del Animations\BWBP4-Anims.ukx
del Animations\BWBP4b-Anims.ukx
del Animations\BWBP4Vehicle-Anims.ukx
del Animations\BWBPAnotherPackAnims.ukx
del Animations\BWBPAnotherPackAnims2.ukx
del Animations\BWBPAnotherPackAnims3.ukx
del Animations\BWBPArchivePack1Anim.ukx
del Animations\BWBPArchivePack2Anim.ukx
del Animations\BWBPJiffyPackAnims.ukx
del Animations\BWBPOtherPackAnim.ukx
del Animations\BWBPOtherPackAnim3.ukx
del Animations\BWBPSomeOtherPackAnims.ukx
del Animations\BWBPWrenchPackAnims.ukx
del Animations\BWSkrithRecolors1Anim.ukx
del Animations\BWSkrithRecolors2Anim.ukx
del Animations\BWWeaponPackAnims.ukx
del Animations\BWXWeaponAnims.ukx
del Animations\JunkWarAnims.ukx
del Animations\BWWeaponPackAnims.ukx
del Animations\BWAddPack-RS-Anims.ukx
del Animations\BallisticExtremeAnims.ukx
del Animations\BallisticExtremeCharacterAnims.ukx
del Animations\BallisticExtremeThird.ukx
del Animations\BallisticThird.ukx
del Animations\BWBPHrDoctorAnim.ukx
del Animations\BallisticRecolors4Anim.ukx
del Animations\BallisticRecolors4AnimA.ukx
del Animations\BallisticRecolors5Anim.ukx
del Animations\BallisticRecolors5AnimA.ukx
del Animations\BWSkrithRecolors1Anim.ukx
del Animations\BWSkrithRecolors2Anim.ukx
del Animations\BallisticRecolors2Anim.ukx
del Animations\BallisticAnims.ukx

del Sounds\BW_Core_WeaponSound.uax
del Sounds\BWBP_CC_Sounds.uax
del Sounds\BWBP_JCF_Sounds.uax
del Sounds\BWBP_JW_Sound.uax
del Sounds\BWBP_OP_Sounds.uax
del Sounds\BWBP_SKC_Sounds.uax
del Sounds\BWBP_SKC_SoundsExp.uax
del Sounds\BWBP_SWC_Sounds.uax
del Sounds\BWBP_APC_Sounds.uax
del Sounds\BWBP_Vehicles_Sound.uax

del Sounds\BallisticProSounds.uax
del Sounds\BallisticSounds_25.uax
del Sounds\BallisticSounds2.uax
del Sounds\BallisticSounds3.uax
del Sounds\BallisticVehicleSounds.uax
del Sounds\BEVehicleSounds.uax
del Sounds\BEVehicleSoundsV13.uax
del Sounds\BWAddPack-RS-Sounds.uax
del Sounds\BWBP1-Sounds2.uax
del Sounds\BWBP2-Sounds.uax
del Sounds\BWBP2-Sounds2.uax
del Sounds\BWBP3-Sounds.uax
del Sounds\BWBP3-Sounds2.uax
del Sounds\BWBP4-Sounds.uax
del Sounds\BWBP4Vehicle-Sounds.uax
del Sounds\BWBPAnotherPackSounds.uax
del Sounds\BWBPAnotherPackSounds2.uax
del Sounds\BWBPArchivePackSounds.uax
del Sounds\BWBPJiffyPackSounds.uax
del Sounds\BWBPOtherPackSound.uax
del Sounds\BWBPSomeOtherPackSounds.uax
del Sounds\BWSkrithRecolorsArchive1Sounds.uax
del Sounds\BWWeaponPack2Archive-Sounds.uax
del Sounds\JunkWarSounds.uax
del Sounds\jwvansound.uax
del Sounds\PackageSounds4Pro.uax
del Sounds\PackageSounds4ProExp.uax
del Sounds\PackageSoundsArchive4.uax
del Sounds\PackageSoundsArchive4A.uax
del Sounds\BWWeaponPack2-Sounds.uax
del Sounds\BWAddPack-RS-Sounds.uax
del Sounds\BallisticExtremeCharacterSounds.uax
del Sounds\BallisticExtremeSnd.uax
del Sounds\BWXWeaponSounds.uax
del Sounds\BWWeaponPack-Sounds.uax
del Sounds\BWBPHrDoctorSounds.uax
del Sounds\PackageSounds4.uax
del Sounds\PackageSounds4A.uax
del Sounds\BWSkrithRecolors1Sounds.uax
del Sounds\BWSkrithRecolors2Sounds.uax
del Sounds\BWWeaponPack2-Sounds.uax
del Sounds\PackageSounds4.uax
del Sounds\PackageSounds4A.uax
del Sounds\PackageSounds5.uax
del Sounds\PackageSounds5A.uax
del Sounds\PackageSounds2.uax
del Sounds\BallisticSounds.uax

del StaticMeshes\BW_Core_WeaponStatic.usx
del StaticMeshes\BWBP_CC_Static.usx
del StaticMeshes\BWBP_JCF_Static.usx
del StaticMeshes\BWBP_JW_Static.usx
del StaticMeshes\BWBP_OP_Static.usx
del StaticMeshes\BWBP_SKC_Static.usx
del StaticMeshes\BWBP_SKC_StaticExp.usx
del StaticMeshes\BWBP_SWC_Static.usx
del StaticMeshes\BWBP_APC_Static.usx
del StaticMeshes\BWBP_Vehicles_Static.usx
del StaticMeshes\BWGoreHardwarePro.usx

del StaticMeshes\BallisticHardware_25.usx
del StaticMeshes\BallisticHardware2.usx
del StaticMeshes\BallisticHardware3.usx
del StaticMeshes\BallisticProStatic.usx
del StaticMeshes\BallisticRecolors4ArchiveStatic.usx
del StaticMeshes\BallisticRecolors4ArchiveStaticA.usx
del StaticMeshes\BallisticRecolors4StaticPro.usx
del StaticMeshes\BallisticRecolors4StaticProExp.usx
del StaticMeshes\BEActorStatics.usx
del StaticMeshes\BEVehicleStatics.usx
del StaticMeshes\BEVehicleStaticsV13.usx
del StaticMeshes\BWAddPack-RS-Hardware.usx
del StaticMeshes\BWBP2Hardware.usx
del StaticMeshes\BWBP3Hardware.usx
del StaticMeshes\BWBP4-Hardware.usx
del StaticMeshes\BWBP4Vehicle-HW.usx
del StaticMeshes\BWBPAnotherPackStatics.usx
del StaticMeshes\BWBPAnotherPackStatics2.usx
del StaticMeshes\BWBPJiffyPackStatic.usx
del StaticMeshes\BWBPOtherPackProjStatic.usx
del StaticMeshes\BWBPOtherPackStatic.usx
del StaticMeshes\BWBPOtherPackStatic3.usx
del StaticMeshes\BWBPSomeOtherPackStatic.usx
del StaticMeshes\BWSkrithRecolorsArchive1Static.usx
del StaticMeshes\BWSkrithRecolorsArchive2Static.usx
del StaticMeshes\BWWeaponPackArchive-Static.usx
del StaticMeshes\BWXWeaponArchiveStatics.usx
del StaticMeshes\JunkWarHardware.usx
del StaticMeshes\JWBPXav-HW.usx
del StaticMeshes\JWVanStatic.usx
del StaticMeshes\BWWeaponPack-Static.usx
del StaticMeshes\BWAddPack-RS-Hardware.usx
del StaticMeshes\BallisticExtremeStatics.usx
del StaticMeshes\BWXWeaponStatics.usx
del StaticMeshes\BWBPHrDoctorStatics.usx
del StaticMeshes\BallisticRecolors4ExpStatic.usx
del StaticMeshes\BallisticRecolors4Static.usx
del StaticMeshes\BallisticRecolors4StaticA.usx
del StaticMeshes\BallisticRecolors4StaticB.usx
del StaticMeshes\BallisticRecolors5Static.usx
del StaticMeshes\BallisticRecolors5StaticA.usx
del StaticMeshes\BWSkrithRecolors1Static.usx
del StaticMeshes\BWSkrithRecolors2Static.usx
del StaticMeshes\BallisticRecolors2Static.usx
del StaticMeshes\BallisticHardware.usx
del StaticMeshes\Ballisticv1_6Hardware.usx
del StaticMeshes\BWGoreHardware.usx

del System\AbaddonBMod.int
del System\AbaddonBMod.u
del System\AbaddonBMod.ucl
del System\BallisticCrosshairs.int
del System\BallisticCrosshairs.u
del System\BallisticCrosshairs.ucl
del System\BallisticDE.ini
del System\BallisticDE.int
del System\BallisticDE.u
del System\BallisticDE.ucl
del System\BCoreDE.int
del System\BCoreDE.u
del System\BWBP_APC_DE.int
del System\BWBP_APC_DE.u
del System\BWBP_APC_DE.ucl
del System\BWBP_JCF_DE.int
del System\BWBP_JCF_DE.u
del System\BWBP_JCF_DE.ucl
del System\BWBP_OP_DE.int
del System\BWBP_OP_DE.u
del System\BWBP_OP_DE.ucl
del System\BWBP_SKC_DE.int
del System\BWBP_SKC_DE.u
del System\BWBP_SKC_DE.ucl
del System\BWBP_SKCExp_DE.int
del System\BWBP_SKCExp_DE.u
del System\BWBP_SKCExp_DE.ucl
del System\BWBP_SWC_DE.int
del System\BWBP_SWC_DE.u
del System\BWBP_SWC_DE.ucl
del System\BWBP_VPC_DE.int
del System\BWBP_VPC_DE.u
del System\BWBP_VPC_DE.ucl
del System\BWCache.ini
del System\BWGuy.upl
del System\BWGuyText.int
del System\BWInteractions3DE.int
del System\BWInteractions3DE.u
del System\BWInteractions3DE.ucl
del System\GunGameBWDE.ini
del System\GunGameBWDE.int
del System\GunGameBWDE.u
del System\GunGameBWDE.ucl
del System\JakobBMod.int
del System\JakobBMod.u
del System\JakobBMod.ucl
del System\KaelaBMod.int
del System\KaelaBMod.u
del System\KaelaBMod.ucl
del System\ZarinaBMod.int
del System\ZarinaBMod.u
del System\ZarinaBMod.ucl
del System\BallisticVehiclesDE.int
del System\BallisticVehiclesDE.u
del System\BallisticVehiclesDE.ucl
del System\BWBPAirstrikesDE.int
del System\BWBPAirstrikesDE.u
del System\BWBPAirstrikesDE.ucl
del System\BWBPAnotherPackDE.int
del System\BWBPAnotherPackDE.u
del System\BWBPAnotherPackDE.ucl
del System\BWBPArchivePackDE.int
del System\BWBPArchivePackDE.u
del System\BWBPArchivePackDE.ucl
del System\BWBPJunkCollectionDE.int
del System\BWBPJunkCollectionDE.u
del System\BWBPJunkCollectionDE.ucl
del System\BWBPOtherPackDE.int
del System\BWBPOtherPackDE.u
del System\BWBPOtherPackDE.ucl
del System\BWBPRecolorsDE.int
del System\BWBPRecolorsDE.u
del System\BWBPRecolorsDE.ucl
del System\GunGameBW.ini
del System\BWBPJiffyPackDE.int
del System\BWBPJiffyPackDE.u
del System\BWBPJiffyPackDE.ucl
del System\BWBPSomeOtherPackDE.int
del System\BWBPSomeOtherPackDE.u
del System\BWBPSomeOtherPackDE.ucl
del System\JunkWarDE.int
del System\JunkWarDE.u
del System\JunkWarDE.ucl
del System\JWVanDE.int
del System\JWVanDE.u
del System\JWVanDE.ucl
del System\BallisticProV55.ini
del System\BallisticProV55.int
del System\BallisticProV55.u
del System\BallisticProV55.ucl
del System\BallisticJiffyPack.int
del System\BallisticJiffyPack.u
del System\BallisticJiffyPack.ucl
del System\BallisticVehiclesPro.int
del System\BallisticVehiclesPro.u
del System\BallisticVehiclesPro.ucl
del System\BCoreProV55.int
del System\BCoreProV55.u
del System\BCoreProV55.ucl
del System\BWBPAirstrikesPro.int
del System\BWBPAirstrikesPro.u
del System\BWBPAirstrikesPro.ucl
del System\BWBPAnotherPackPro.int
del System\BWBPAnotherPackPro.u
del System\BWBPAnotherPackPro.ucl
del System\BWBPArchivePackPro.ini
del System\BWBPArchivePackPro.int
del System\BWBPArchivePackPro.u
del System\BWBPArchivePackPro.ucl
del System\BWBPOtherPackPro.int
del System\BWBPOtherPackPro.u
del System\BWBPOtherPackPro.ucl
del System\BWBPOtherPack2Pro.int
del System\BWBPOtherPack2Pro.u
del System\BWBPOtherPack2Pro.ucl
del System\BWBPRecolorsPro.int
del System\BWBPRecolorsPro.u
del System\BWBPRecolorsPro.ucl
del System\BWBPSomeOtherPack.int
del System\BWBPSomeOtherPack.u
del System\BWBPSomeOtherPack.ucl
del System\BWInteractions3.int
del System\BWInteractions3.u
del System\BWInteractions3.ucl
del System\JunkWar.int
del System\JunkWar.u
del System\JunkWar.ucl
del System\JunkWarPro.ini
del System\JunkWarPro.int
del System\JunkWarPro.u
del System\JunkWarPro.ucl
del System\JWVan.int
del System\JWVan.u
del System\JWVan.ucl
del System\3SPNv3141.int
del System\3SPNv3141.u
del System\3SPNv3141.ucl
del System\Ballistic.int
del System\BEVehiclesV14.int
del System\BEVehiclesV14.u
del System\BEVehiclesV14.ucl
del System\LDGGameBW_rc.ini
del System\LDGGameBW_rc.int
del System\LDGGameBW_rc.u
del System\LDGGameBW_rc.ucl
del System\BWBP4.int
del System\BWBP4Vehicles.int
del System\BWBP4Vehicles.u
del System\BWBP4Vehicles.ucl
del System\BWBPFour.int
del System\BWBPFour.u
del System\BWBPFour.ucl
del System\BWBPFourB.int
del System\BWBPFourB.u
del System\BWBPFourB.ucl
del System\BWBPThree.int
del System\BWBPThree.u
del System\BWBPThree.ucl
del System\BWBPTwo.int
del System\BWBPTwo.u
del System\BWBPTwo.ucl
del System\BWBPOneV2.int
del System\BWBPOneV2.u
del System\BWBPOneV2.ucl
del System\BWBPWeaponPack2.int
del System\BWBPWeaponPack2.u 
del System\BWBPWeaponPack2.ucl
del System\RedGunPack.int
del System\RedGunPack.u
del System\RedGunPack.ucl
del System\BallisticCharactersExtreme.int
del System\BallisticCharactersExtreme.u
del System\BallisticCharactersExtreme.ucl
del System\BallisticExtreme.ini
del System\BallisticExtreme.int
del System\BallisticExtreme.u
del System\BallisticExtreme.ucl
del System\BallisticExtreme.upl
del System\BallisticVehiclesExtreme.int
del System\BallisticVehiclesExtreme.u
del System\BallisticVehiclesExtreme.ucl
del System\BCoreExtreme.int
del System\BCoreExtreme.u
del System\BCoreExtreme.ucl
del System\BWXWeapon.int
del System\BWXWeapon.u
del System\BWXWeapon.ucl
del System\BWBPWeaponPack.int
del System\BWBPWeaponPack.u
del System\BWBPWeaponPack.ucl
del System\BallisticFix.int
del System\BallisticFix.u
del System\BallisticFix.ucl
del System\BallisticVehiclesFix.int
del System\BallisticVehiclesFix.u
del System\BallisticVehiclesFix.ucl
del System\BCoreFix.int
del System\BCoreFix.u
del System\BCoreFix.ucl
del System\BWBPWeaponPackFix.int
del System\BWBPWeaponPackFix.u
del System\BWBPWeaponPackFix.ucl
del System\JunkWarFix.int
del System\JunkWarFix.u
del System\JunkWarFix.ucl
del System\BWBPAirstrikes.int
del System\BWBPAirstrikes.u
del System\BWBPAirstrikes.ucl
del System\BWBPOtherPack.int
del System\BWBPOtherPack.u
del System\BWBPOtherPack.ucl
del System\BWBPHrDoctor.int
del System\BWBPHrDoctor.u
del System\BWBPHrDoctor.ucl
del System\BWBPRecolors4ExpG.int
del System\BWBPRecolors4ExpG.u
del System\BWBPRecolors4ExpG.ucl
del System\BWBPRecolors4Main.int
del System\BWBPRecolors4Main.u
del System\BWBPRecolors4Main.ucl
del System\LDGAbstractBalancer.u
del System\LDGFlags.u
del System\LDGGameBW.u
del System\LDGGameBW_rc.u
del System\LDGNetSpeed3.u
del System\LDGVote30.u
del System\BallisticV21.ini
del System\BallisticV21.int
del System\BallisticV21.u
del System\BallisticV21.ucl
del System\BWBPRecolors2.int
del System\BWBPRecolors2.u
del System\BWBPRecolors2.ucl
del System\BWBPRecolors4Exp.int
del System\BWBPRecolors4Exp.u
del System\BWBPRecolors4Exp.ucl
del System\Ballistic.int
del System\Ballistic.u
del System\Ballistic.ucl
del System\Itemizer.ini
del System\BCore.int
del System\BCore.u
del System\BCore.ucl
del System\BCoreV2.int
del System\BCoreV2.u
del System\BCoreV2.ucl
del System\BallisticV2.int
del System\BallisticV2.u
del System\BallisticV2.ucl
del System\JunkWarV2.int
del System\JunkWarV2.u
del System\JunkWarV2.ucl
del System\BallisticVehicles.int
del System\BallisticVehicles.u
del System\BallisticVehicles.ucl
del System\BCoreV21.int
del System\BCoreV21.u
del System\BCoreV21.ucl
del System\BWBPOneV21.int
del System\BWBPOneV21.u
del System\BWBPOneV21.ucl
del System\BWBPTwoV21.int
del System\BWBPTwoV21.u
del System\BWBPTwoV21.ucl
del System\BWBPThreeV21.int
del System\BWBPThreeV21.u
del System\BWBPThreeV21.ucl
del System\JunkWarV21.int
del System\JunkWarV21.u
del System\JunkWarV21.ucl
del System\BallisticV25.int
del System\BallisticV25.u
del System\BallisticV25.ucl
del System\BallisticVehiclesV25.ini
del System\BallisticVehiclesV25.int
del System\BallisticVehiclesV25.u
del System\BallisticVehiclesV25.ucl
del System\BCoreV25.int
del System\BCoreV25.u
del System\BCoreV25.ucl
del System\BEVehicles.int
del System\BEVehicles.u
del System\BEVehicles.ucl
del System\JunkWarV25.ini
del System\JunkWarV25.int
del System\JunkWarV25.u
del System\JunkWarV25.ucl
del System\BWBP_APC_Pro.int
del System\BWBP_APC_Pro.u
del System\BWBP_APC_Pro.ucl
del System\BWBP_JCF_Pro.int
del System\BWBP_JCF_Pro.u
del System\BWBP_JCF_Pro.ucl
del System\BWBP_OP_Pro.int
del System\BWBP_OP_Pro.u
del System\BWBP_OP_Pro.ucl
del System\BWBP_SKC_Pro.int
del System\BWBP_SKC_Pro.u
del System\BWBP_SKC_Pro.ucl
del System\BWBP_SWC_Pro.int
del System\BWBP_SWC_Pro.u
del System\BWBP_SWC_Pro.ucl
del System\BWBP_VPC_Pro.int
del System\BWBP_VPC_Pro.u
del System\BWBP_VPC_Pro.ucl
del System\3SPNv3141BW.int
del System\3SPNv3141BW.u
del System\3SPNv3141BW.ucl
del System\GunGameBW.int
del System\GunGameBW.u
del System\GunGameBW.ucl

del Textures\BallisticBloodPro.utx
del Textures\BW_Core_WeaponTex.utx
del Textures\BWBP_Camos_Tex.utx
del Textures\BWBP_CC_Tex.utx
del Textures\BWBP_JCF_Tex.utx
del Textures\BWBP_JW_Tex.utx
del Textures\BWBP_OP_Tex.utx
del Textures\BWBP_SKC_Tex.utx
del Textures\BWBP_SKC_TexExp.utx
del Textures\BWBP_SWC_Tex.utx
del Textures\BWBP_APC_Tex.utx
del Textures\BWBP_Vehicles_Tex.utx
del Textures\BWGuyTex.utx

del Textures\BallisticEffects.utx
del Textures\BallisticEffects2.utx
del Textures\BallisticItems.utx
del Textures\BallisticProTextures.utx
del Textures\BallisticRecolors3TexPro.utx
del Textures\BallisticRecolors4.utx
del Textures\BallisticRecolors4A.utx
del Textures\BallisticRecolors4B.utx
del Textures\BallisticRecolors4Exp.utx
del Textures\BallisticRecolors4TexPro.utx
del Textures\BallisticRecolorsArchive4.utx
del Textures\BallisticRecolorsArchive4A.utx
del Textures\BallisticRecolorsArchive5.utx
del Textures\BallisticRecolorsArchive5A.utx
del Textures\BallisticTextures_25.utx
del Textures\BallisticTextures3.utx
del Textures\BallisticUI.utx
del Textures\BallisticUI2.utx
del Textures\BallisticWeapons2.utx
del Textures\BEActorTex.utx
del Textures\BEVehicleSkins.utx
del Textures\BEVehicleSkinsV13.utx
del Textures\BWAddPack-RS-Effects.utx
del Textures\BWAddPack-RS-Skins.utx
del Textures\BWBP2-FX.utx
del Textures\BWBP2-Tex.utx
del Textures\BWBP3-Tex.utx
del Textures\BWBP4-Tex.utx
del Textures\BWBP4Vehicle-Tex.utx
del Textures\BWBPAnotherPackTex.utx
del Textures\BWBPAnotherPackTex2.utx
del Textures\BWBPAnotherPackTex3.utx
del Textures\BWBPArchivePackTex.utx
del Textures\BWBPJiffyPackTex.utx
del Textures\BWBPOtherPackProjTex.utx
del Textures\BWBPOtherPackTex.utx
del Textures\BWBPOtherPackTex2.utx
del Textures\BWBPOtherPackTex3.utx
del Textures\BWBPOtherPackTex4.utx
del Textures\BWBPSomeOtherPackTex.utx
del Textures\BWBPWrenchPackTex.utx
del Textures\BWEliminationTex.utx
del Textures\BWSkrithRecolorsArchive1Tex.utx
del Textures\BWSkrithRecolorsArchive2Tex.utx
del Textures\BWWeaponPackArchive-Tex.utx
del Textures\BWXWeaponArchiveTex.utx
del Textures\JunkWarSkins.utx
del Textures\JunkWarUI.utx
del Textures\JunkWarUI2.utx
del Textures\JWBPXav-Tex.utx
del Textures\jwvantex.utx
del Textures\R9A_tex.utx
del Textures\BWWeaponPack-Tex.utx
del Textures\BallisticExtremeCharacterTex.utx
del Textures\BallisticExtremeTex.utx
del Textures\BWXWeaponTex.utx
del Textures\BWBPHrDoctorTex.utx
del Textures\BWSkrithRecolors1Tex.utx
del Textures\BWSkrithRecolors2Tex.utx
del Textures\BallisticRecolors5.utx
del Textures\BallisticRecolors5A.utx
del Textures\BallisticRecolors2.utx
del Textures\BallisticBlood.utx
del Textures\Ballisticv1_6Tex.utx
del Textures\BallisticWeapons.utx
del Textures\BallisticBlood2.utx
del Textures\BallisticBlood3.utx
del Textures\BallisticBlood25.utx

echo The uninstaller was last used on %DATE% %TIME% > "BW uninstaller.log"

pause