//=============================================================================
// Ammo_HKMK 23.
//
// 45.ACP Low Velocity Pistol bullets for the HKMK 23.
//
// by Fischer Felix
//=============================================================================
class Ammo_HKMKSpecBullets extends BallisticAmmo;

defaultproperties
{
     MaxAmmo=64
     InitialAmount=32
     IconFlashMaterial=Shader'BWBP_JCF_Tex.MK23.AmmoIcon_MK23Flash'
     PickupClass=Class'BWBP_JCF_Pro.AP_HKMKSpecBullets'
     IconMaterial=Texture'BWBP_JCF_Tex.MK23.AmmoIcon_MK23'
     IconCoords=(X2=63,Y2=63)
     ItemName="45. ACP Bullets"
}
