//=============================================================================
// Ammo_556mm.
//
// 5.56mm bullet ammo. Used by several of the ballistic weapons.
//
// by Nolan "Dark Carnivour" Richert.
// Copyright(c) 2005 RuneStorm. All Rights Reserved.
//=============================================================================
class Ammo_447mm extends BallisticAmmo;

defaultproperties
{
     MaxAmmo=105
     InitialAmount=70
     IconFlashMaterial=Shader'BWBP_JCF_Tex.M7A3.AmmoIcon_M7A3Flash'
     PickupClass=Class'BWBP_JCF_Pro.AP_M7A3Clip'
     IconMaterial=Texture'BWBP_JCF_Tex.M7A3.AmmoIcon_M7A3'
     IconCoords=(X1=128,X2=191,Y2=63)
     ItemName="4.77mm Ammo"
}
