//=============================================================================
// Brass_Rifle.
//
// A rifle shell casing
//
// by Nolan "Dark Carnivour" Richert.
// Copyright(c) 2005 RuneStorm. All Rights Reserved.
//=============================================================================
class Brass_50BMG extends BWBrass_Default;

defaultproperties
{
     StartVelocity=(Z=150.000000)
     StaticMesh=StaticMesh'BW_Core_WeaponStatic.Brass.EmptyRifleRound'
     DrawScale=0.300000
}
