//=============================================================================
// DTGRS9Pistol.
//
// Damage type for the GRS9 Pistol
//
// by Nolan "Dark Carnivour" Richert.
// Copyright(c) 2007 RuneStorm. All Rights Reserved.
//=============================================================================
class DTHKMKSpecPistol extends DT_BWBullet;

defaultproperties
{
     DeathStrings(0)="%o's escape velocity was pitiful compared to the .45HV bullets that %k's slinging."
     DeathStrings(1)="%k took out the prime suspect, %o, with several bullets to the kidneys."
     DeathStrings(2)="%o won't be running from the law anymore, or living at all thanks to %k."
     DeathStrings(3)="%k tore into %o's ankles with some very speedy .45 bullets."
     DeathStrings(4)="%o not only had their body armor pierced, but their lungs as well due to taking %k's bullets."
     DeathStrings(5)="%k blew through %o's armor like a laser cutter through butter."
     WeaponClass=Class'BWBP_JCF_Pro.HKMKSpecPistol'
     DeathString="%k drew %kh HKM-26 too fast for %o to react."
     FemaleSuicide="%o prosecuted herself with the HKM-26."
     MaleSuicide="%o prosecuted himself with the HKM-26."
     VehicleDamageScaling=0.750000
}
