//=============================================================================
// DTM7A3Rifle.
//
// Damage type for the M7A3
//
// by Nolan "Dark Carnivour" Richert.
// Copyright(c) 2007 RuneStorm. All Rights Reserved.
//=============================================================================
class DTM7A3Rifle extends DT_BWBullet;

defaultproperties
{
     DeathStrings(0)="%o's torso was ripped to shreds by %k's M7A3."
     DeathStrings(1)="%k preforated %o with %kh M7A3."
     DeathStrings(2)="%k's M7A3 filled %o with bloody holes."
     DeathStrings(3)="%k's M7A3 cut down a fleeing %o."
     DeathStrings(4)="%k tactically deleted %o with %kh M7A3."
     DeathStrings(5)="%k hailstormed %o with M7A3 bullets."
     DeathStrings(6)="%k's M7A3 cleared the room %o was hiding in."
     EffectChance=0.500000
     WeaponClass=Class'BWBP_JCF_Pro.M7A3AssaultRifle'
     DeathString="%o's torso was ripped to shreds by %k's M7A3."
     FemaleSuicide="%o murdificated herself."
     MaleSuicide="%o murdurified himself."
     bFastInstantHit=True
     VehicleDamageScaling=0.600000
}
