//=============================================================================
// DTM99Rifle.
//
// Damage type for the M99 Sniper Rifle
//
// by Sergeant Kelly
// Copyright(c) 2010 RuneStorm. All Rights Reserved.
//=============================================================================
class DTM99Rifle extends DT_BWBullet;

defaultproperties
{
     DeathStrings(0)="%o was gutted by %k's huge M99-ECS round."
     DeathStrings(1)="%k directed a .55 cal M99-ECS slug into %o's chest."
     DeathStrings(2)="%k pierced an unfortunate %o with %kh M99-ECS."
     DeathStrings(3)="%k assassinated %o with a single M99 shot."
     WeaponClass=Class'BWBP_JCF_Pro.M99Rifle'
     DeathString="%o was silenced by %k's M99-ECS."
     FemaleSuicide="%o held her M99-ECS the wrong way around."
     MaleSuicide="%o held his M99-ECS the wrong way around."
     VehicleDamageScaling=3.0000
}
