name: Bug report
description: Something did not work or crashed the game.
labels: [Bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description of the bug
      description: |
          Please describe the steps to reproduce as detailed as possible. Attach
          relevant settings files (careful, these are public). For UnrealEd
          bugs, please attach test maps that demonstrate the issue.
      placeholder: (Required)
    validations:
      required: true
  - type: textarea
    id: actions
    attributes:
      label: How to reproduce
      description: |
          Please describe the steps to reproduce the bug as detailed as possible. Attach
          relevant pictures or UT2004.log that can be found in the UT2004 system folder
      placeholder: (Required)
    validations:
      required: true
  - type: input
    id: bw-version
    attributes:
      label: Ballistic Weapons Version
      description: On which version of Ballistic Weapons did the bug appear on?
    validations:
      required: true
  - type: input
    id: gamestyle
    attributes:
      label: Gamestyle used
      description: On which gamestyle did the bug appear on?
    validations:
      required: true
  - type: input
    id: off/online
    attributes:
      label: Offline or Online?
      description: Did the bug appear in a offline or online environment?
    validations:
      required: true    
  - type: input
    id: ut2004-version
    attributes:
      label: UT2004 Version
      description: On which version of UT2004 did the bug appear on?
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: If there is anything else that might help figuring out whats wrong, please enter it here.
