

defaultproperties
{
     UTCompMenuClass="UTCompv17a.UTComp_Menu_OpenedMenu"
     UTCompVotingMenuClass="UTCompv17a.UTComp_Menu_VoteInProgress"
     redmessagecolor=(B=64,G=64,R=255,A=255)
     greenmessagecolor=(B=128,G=255,R=128,A=255)
     bluemessagecolor=(B=255,G=192,R=64,A=255)
     yellowmessagecolor=(G=255,R=255,A=255)
     graymessagecolor=(B=155,G=155,R=255)
     WepStatNames(0)="Combo"
     WepStatNames(1)="I-Gib"
     WepStatNames(2)="AVRIL"
     WepStatNames(3)="Grenades"
     WepStatNames(4)="Spider"
     WepStatNames(5)="Sniper"
     WepStatNames(6)="Rockets"
     WepStatNames(7)="Flak"
     WepStatNames(8)="Mini"
     WepStatNames(9)="Link"
     WepStatNames(10)="Shock"
     WepStatNames(11)="Bio"
     WepStatNames(12)="Assault"
     WepStatNames(13)="Shield"
     WepStatNames(14)="Crush"
     WepStatDamTypesAlt(6)=Class'XWeapons.DamTypeRocketHoming'
     WepStatDamTypesAlt(7)=Class'XWeapons.DamTypeFlakShell'
     WepStatDamTypesAlt(8)=Class'XWeapons.DamTypeMinigunAlt'
     WepStatDamTypesAlt(9)=Class'XWeapons.DamTypeLinkShaft'
     WepStatDamTypesAlt(10)=Class'XWeapons.DamTypeShockBall'
     WepStatDamTypesAlt(12)=Class'XWeapons.DamTypeAssaultGrenade'
     WepStatDamTypesPrim(0)=Class'XWeapons.DamTypeShockCombo'
     WepStatDamTypesPrim(1)=Class'XWeapons.DamTypeSuperShockBeam'
     WepStatDamTypesPrim(2)=Class'Onslaught.DamTypeONSAVRiLRocket'
     WepStatDamTypesPrim(3)=Class'Onslaught.DamTypeONSGrenade'
     WepStatDamTypesPrim(4)=Class'Onslaught.DamTypeONSMine'
     WepStatDamTypesPrim(5)=Class'XWeapons.DamTypeSniperShot'
     WepStatDamTypesPrim(6)=Class'XWeapons.DamTypeRocket'
     WepStatDamTypesPrim(7)=Class'XWeapons.DamTypeFlakChunk'
     WepStatDamTypesPrim(8)=Class'XWeapons.DamTypeMinigunBullet'
     WepStatDamTypesPrim(9)=Class'XWeapons.DamTypeLinkPlasma'
     WepStatDamTypesPrim(10)=Class'XWeapons.DamTypeShockBeam'
     WepStatDamTypesPrim(11)=Class'XWeapons.DamTypeBioGlob'
     WepStatDamTypesPrim(12)=Class'XWeapons.DamTypeAssaultBullet'
     WepStatDamTypesPrim(13)=Class'XWeapons.DamTypeShieldImpact'
     WepStatDamTypesPrim(14)=Class'Engine.Crushed'
     CustomWepTypes(0)=(WepName="Manta",damtype[0]="Onslaught.DamTypeHoverBikePancake",damtype[1]="Onslaught.DamTypeHoverBikeHeadshot",damtype[2]="Onslaught.DamTypeHoverBikePlasma")
     CustomWepTypes(1)=(WepName="Raptor",damtype[0]="Onslaught.DamTypeAttackCraftPancake",damtype[1]="Onslaught.DamTypeAttackCraftRoadkill",damtype[2]="Onslaught.DamTypeAttackCraftMissle",damtype[3]="Onslaught.DamTypeAttackCraftPlasma")
     CustomWepTypes(2)=(WepName="HBender",damtype[0]="Onslaught.DamTypePRVPancake",damtype[1]="Onslaught.DamTypePRVRoadkill",damtype[2]="Onslaught.DamTypePRVCombo",damtype[3]="Onslaught.DamTypePRVLaser",damtype[4]="Onslaught.DamTypeChargingBeam",damtype[5]="Onslaught.DamTypeSkyMine")
     CustomWepTypes(3)=(WepName="Scorpion",damtype[0]="Onslaught.DamTypeRVPancake",damtype[1]="Onslaught.DamTypeRVRoadkill",damtype[2]="Onslaught.DamTypeONSRVBlade",damtype[3]="Onslaught.DamTypeONSWeb")
     CustomWepTypes(4)=(WepName="Goliath",damtype[0]="Onslaught.DamTypeTankPancake",damtype[1]="Onslaught.DamTypeTankRoadkill",damtype[2]="Onslaught.DamTypeTankShell")
     CustomWepTypes(5)=(WepName="Leviath",damtype[0]="OnslaughtFull.DamTypeMASCannon",damtype[1]="OnslaughtFull.DamTypeMASPlasma",damtype[2]="OnslaughtFull.DamTypeMASRoadKill",damtype[3]="OnslaughtFull.DamTypeMASPanCake")
     CustomWepTypes(6)=(WepName="Fighter",damtype[0]="UT2k4AssaultFull.DamTypeSpaceFighterLaser",damtype[1]="UT2k4AssaultFull.DamTypeSpaceFighterLaser_Skaarj",damtype[2]="UT2k4AssaultFull.DamTypeSpaceFighterMissile",damtype[3]="UT2k4AssaultFull.DamTypeSpaceFighterMissileSkaarj")
     CustomWepTypes(7)=(WepName="IonTank",damtype[0]="OnslaughtFull.DamTypeIonTankBlast",damtype[1]="UT2k4AssaultFull.DamTypeIonCannonBlast")
     CustomWepTypes(8)=(WepName="SuperWep",damtype[0]="XWeapons.DamTypeRedeemer",damtype[1]="XWeapons.DamTypeIonBlast")
     CustomWepTypes(9)=(WepName="Paladin",damtype[0]="OnslaughtBP.DamTypeShockTankProximityExplosion",damtype[1]="OnslaughtBP.DamTypeShockTankShockBall")
     CustomWepTypes(10)=(WepName="Cicada",damtype[0]="OnslaughtBP.DamTypeONSCicadaRocket",damtype[1]="OnslaughtBP.DamTypeONSCicadaLaser")
     CustomWepTypes(11)=(WepName="SPMA",damtype[0]="OnslaughtBP.DamTypeArtilleryShell")
     CustomWepTypes(12)=(WepName="XxxX ESR",damtype[0]="XxxXESRInstaGib",damtype[1]="XxxXESRHeadshot")
}
