

defaultproperties
{
     bEnableVoting=True
     bEnableBrightskinsVoting=True
     bEnableHitsoundsVoting=True
     bEnableWarmupVoting=True
     bEnableTeamOverlayVoting=True
     bEnableMapVoting=True
     bEnableGametypeVoting=True
     bEnableTimedOvertimeVoting=True
     VotingPercentRequired=51.000000
     VotingTimeLimit=30.000000
     benableDoubleDamage=True
     EnableBrightSkinsMode=3
     bEnableClanSkins=True
     bEnableTeamOverlay=True
     EnableHitSoundsMode=1
     bEnableScoreboard=True
     bEnableWarmup=True
     WarmupReadyPercentRequired=100.000000
     bEnableWeaponStats=True
     bEnablePowerupStats=True
     bShowTeamScoresInServerBrowser=True
     ServerMaxPlayers=12
     bEnableAdvancedVotingOptions=True
     AlwaysUseThisMutator(0)="UTCompv17a.mututcomp"
     AutoDemoRecMask="%d-(%t)-%m-%p"
     EnableWarmupWeaponsMode=1
     WarmupHealth=199
     bForceMapVoteMatchPrefix=True
     TimedOverTimeLength=300
     NumGrenadesOnSpawn=4
     bEnableForwardVoting=True
     bShieldFix=True
     VotingGametype(0)=(GametypeOptions="?game=XGame.xDeathMatch?timelimit=15?minplayers=0?goalscore=0?Mutator=XWeapons.MutNoSuperWeapon,XGame.MutNoAdrenaline?weaponstay=false?DoubleDamage=false?GrenadesOnSpawn=4?TimedOverTimeLength=0",GametypeName="1v1")
     VotingGametype(1)=(GametypeOptions="?game=XGame.xDeathMatch?timelimit=15?minplayers=0?goalscore=50?weaponstay=True?DoubleDamage=True?GrenadesOnSpawn=4?TimedOverTimeLength=0",GametypeName="FFA")
     VotingGametype(2)=(GametypeOptions="?game=XGame.xTeamGame?timelimit=20?goalscore=0?minplayers=0?Mutator=XWeapons.MutNoSuperWeapon?FriendlyfireScale=1.00?weaponstay=False?DoubleDamage=True?GrenadesOnSpawn=1?TimedOverTimeLength=5",GametypeName="Team Deathmatch")
     VotingGametype(3)=(GametypeOptions="?game=XGame.xCTFGame?timelimit=20?goalscore=0?minplayers=0?mutator=XGame.MutNoAdrenaline,XWeapons.MutNoSuperWeapon?friendlyfirescale=0?weaponstay=true?DoubleDamage=True?GrenadesOnSpawn=4?TimedOverTimeLength=0",GametypeName="Capture the Flag")
     VotingGametype(4)=(GametypeOptions="?game=Onslaught.ONSOnslaughtGame?timelimit=20?goalscore=1?mutator=XWeapons.MutNoSuperWeapon?minplayers=0?friendlyfirescale=0?weaponstay=True?DoubleDamage=True?GrenadesOnSpawn=4?TimedOverTimeLength=0",GametypeName="Onslaught")
     VotingGametype(5)=(GametypeOptions="?game=UTCompv17a.UTComp_ClanArena?goalscore=7?TimeLimit=2?FriendlyFireScale=0?GrenadesOnSpawn=4?TimedOverTimeLength=0",GametypeName="Clan Arena")
     VotingGametype(6)=(GametypeOptions="?game=UT2k4Assault.ASGameInfo?timelimit=20?goalscore=1?FriendlyFireScale=0,WeaponStay=true?mutator=XWeapons.MutNoSuperWeapon?DoubleDamage=true?GrenadesOnSpawn=4?TimedOverTimeLength=0",GametypeName="Assault")
     VotingGametype(7)=(GametypeOptions="?game=XGame.xDoubleDom?timelimit=20?goalscore=0?FriendlyFireScale=0,WeaponStay=true?mutator=XWeapons.MutNoSuperWeapon?DoubleDamage=true?GrenadesOnSpawn=4?TimedOverTimeLength=0",GametypeName="Double Domination")
     VotingGametype(8)=(GametypeOptions="?game=XGame.xBombingRun?timelimit=20?goalscore=0?FriendlyFireScale=0,WeaponStay=True?mutator=XWeapons.MutNoSuperWeapon?DoubleDamage=True?GrenadesOnSpawn=4?TimedOverTimeLength=0",GametypeName="Bombing Run")
     bEnableEnhancedNetCodeVoting=True
     WeaponClasses(0)=Class'utcompv17a.NewNet_ShockRifle'
     WeaponClasses(1)=Class'utcompv17a.NewNet_LinkGun'
     WeaponClasses(2)=Class'utcompv17a.newNet_MiniGun'
     WeaponClasses(3)=Class'utcompv17a.NewNet_FlakCannon'
     WeaponClasses(4)=Class'utcompv17a.NewNet_RocketLauncher'
     WeaponClasses(5)=Class'utcompv17a.NewNet_SniperRifle'
     WeaponClasses(6)=Class'utcompv17a.NewNet_BioRifle'
     WeaponClasses(7)=Class'utcompv17a.NewNet_AssaultRifle'
     WeaponClasses(8)=Class'utcompv17a.NewNet_ClassicSniperRifle'
     WeaponClasses(9)=Class'utcompv17a.NewNet_ONSAvril'
     WeaponClasses(10)=Class'utcompv17a.NewNet_ONSMineLayer'
     WeaponClasses(11)=Class'utcompv17a.NewNet_ONSGrenadeLauncher'
     WeaponClassNames(0)="xWeapons.ShockRifle"
     WeaponClassNames(1)="xWeapons.LinkGun"
     WeaponClassNames(2)="xWeapons.MiniGun"
     WeaponClassNames(3)="xWeapons.FlakCannon"
     WeaponClassNames(4)="xWeapons.RocketLauncher"
     WeaponClassNames(5)="xWeapons.SniperRifle"
     WeaponClassNames(6)="xWeapons.BioRifle"
     WeaponClassNames(7)="xWeapons.AssaultRifle"
     WeaponClassNames(8)="UTClassic.ClassicSniperRifle"
     WeaponClassNames(9)="Onslaught.ONSAVRiL"
     WeaponClassNames(10)="Onslaught.ONSMineLayer"
     WeaponClassNames(11)="Onslaught.ONSGrenadeLauncher"
     ReplacedWeaponClasses(0)=Class'XWeapons.ShockRifle'
     ReplacedWeaponClasses(1)=Class'XWeapons.LinkGun'
     ReplacedWeaponClasses(2)=Class'XWeapons.Minigun'
     ReplacedWeaponClasses(3)=Class'XWeapons.FlakCannon'
     ReplacedWeaponClasses(4)=Class'XWeapons.RocketLauncher'
     ReplacedWeaponClasses(5)=Class'XWeapons.SniperRifle'
     ReplacedWeaponClasses(6)=Class'XWeapons.BioRifle'
     ReplacedWeaponClasses(7)=Class'XWeapons.AssaultRifle'
     ReplacedWeaponClasses(8)=Class'UTClassic.ClassicSniperRifle'
     ReplacedWeaponClasses(9)=Class'Onslaught.ONSAVRiL'
     ReplacedWeaponClasses(10)=Class'Onslaught.ONSMineLayer'
     ReplacedWeaponClasses(11)=Class'Onslaught.ONSGrenadeLauncher'
     ReplacedWeaponPickupClasses(0)=Class'XWeapons.ShockRiflePickup'
     ReplacedWeaponPickupClasses(1)=Class'XWeapons.LinkGunPickup'
     ReplacedWeaponPickupClasses(2)=Class'XWeapons.MinigunPickup'
     ReplacedWeaponPickupClasses(3)=Class'XWeapons.FlakCannonPickup'
     ReplacedWeaponPickupClasses(4)=Class'XWeapons.RocketLauncherPickup'
     ReplacedWeaponPickupClasses(5)=Class'XWeapons.SniperRiflePickup'
     ReplacedWeaponPickupClasses(6)=Class'XWeapons.BioRiflePickup'
     ReplacedWeaponPickupClasses(7)=Class'XWeapons.AssaultRiflePickup'
     ReplacedWeaponPickupClasses(8)=Class'UTClassic.ClassicSniperRiflePickup'
     ReplacedWeaponPickupClasses(9)=Class'Onslaught.ONSAVRiLPickup'
     ReplacedWeaponPickupClasses(10)=Class'Onslaught.ONSMineLayerPickup'
     ReplacedWeaponPickupClasses(11)=Class'Onslaught.ONSGrenadePickup'
     WeaponPickupClasses(0)=Class'utcompv17a.NewNet_ShockRiflePickup'
     WeaponPickupClasses(1)=Class'utcompv17a.NewNet_LinkGunPickup'
     WeaponPickupClasses(2)=Class'utcompv17a.NewNet_MiniGunPickup'
     WeaponPickupClasses(3)=Class'utcompv17a.NewNet_FlakCannonPickup'
     WeaponPickupClasses(4)=Class'utcompv17a.NewNet_RocketLauncherPickup'
     WeaponPickupClasses(5)=Class'utcompv17a.NewNet_SniperRiflePickup'
     WeaponPickupClasses(6)=Class'utcompv17a.NewNet_BioRiflePickup'
     WeaponPickupClasses(7)=Class'utcompv17a.NewNet_AssaultRiflePickup'
     WeaponPickupClasses(8)=Class'utcompv17a.NewNet_ClassicSniperRiflePickup'
     WeaponPickupClasses(9)=Class'utcompv17a.NewNet_ONSAVRiLPickup'
     WeaponPickupClasses(10)=Class'utcompv17a.NewNet_ONSMineLayerPickup'
     WeaponPickupClasses(11)=Class'utcompv17a.NewNet_ONSGrenadePickup'
     WeaponPickupClassNames(0)="UTCompv17a.NewNet_ShockRiflePickup"
     WeaponPickupClassNames(1)="UTCompv17a.NewNet_LinkGunPickup"
     WeaponPickupClassNames(2)="UTCompv17a.NewNet_MiniGunPickup"
     WeaponPickupClassNames(3)="UTCompv17a.NewNet_FlakCannonPickup"
     WeaponPickupClassNames(4)="UTCompv17a.NewNet_RocketLauncherPickup"
     WeaponPickupClassNames(5)="UTCompv17a.NewNet_SniperRiflePickup"
     WeaponPickupClassNames(6)="UTCompv17a.NewNet_BioRiflePickup"
     WeaponPickupClassNames(7)="UTCompv17a.NewNet_AssaultRiflePickup"
     WeaponPickupClassNames(8)="UTCompv17a.NewNet_ClassicSniperRiflePickup"
     WeaponPickupClassNames(9)="UTCompv17a.NewNet_ONSAVRiLPickup"
     WeaponPickupClassNames(10)="UTCompv17a.NewNet_ONSMineLayerPickup"
     WeaponPickupClassNames(11)="UTCompv17a.NewNet_ONSGrenadePickup"
     bAddToServerPackages=True
     FriendlyName="UTComp Version 1.7a"
     Description="A mutator for warmup, brightskins, hitsounds, and various other features."
     bNetTemporary=True
     bAlwaysRelevant=True
     RemoteRole=ROLE_SimulatedProxy
}
