//=============================================================================
// DTXK2SMG.
//
// by Nolan "Dark Carnivour" Richert.
// Copyright(c) 2005 RuneStorm. All Rights Reserved.
//=============================================================================
class DTT9CN extends DT_BWBullet;

defaultproperties
{
     DeathStrings(0)="%o danced through %k's T9CN lead."
     DeathStrings(1)="%k cut short %o's cry with a T9CN Automatic Pistol."
     DeathStrings(2)="%k went spec-ops on %o with T9CN rounds."
     DeathStrings(3)="%o couldn't match the efficiency of %k's T9CN."
     EffectChance=0.500000
     WeaponClass=Class'BWBP_SKC_Pro.T9CNMachinePistol'
     DeathString="%o danced through %k's T9CN lead."
     FemaleSuicide="%o silenced herself."
     MaleSuicide="%o silenced himself."
     bFastInstantHit=True
     VehicleDamageScaling=0.750000
}
